// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function HealthCheck():Promise<Record<string, any>>;

export function LogMessage(arg1:string,arg2:string):Promise<void>;
