// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAgentExecution(arg1) {
  return window['go']['main']['App']['CancelAgentExecution'](arg1);
}

export function ExecuteAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteAgent'](arg1, arg2, arg3);
}

export function GetAgentExecutions() {
  return window['go']['main']['App']['GetAgentExecutions']();
}

export function GetAgentStatus(arg1) {
  return window['go']['main']['App']['GetAgentStatus'](arg1);
}

export function GetAllAgentsStatus() {
  return window['go']['main']['App']['GetAllAgentsStatus']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function LogMessage(arg1, arg2) {
  return window['go']['main']['App']['LogMessage'](arg1, arg2);
}
