// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function LogMessage(arg1, arg2) {
  return window['go']['main']['App']['LogMessage'](arg1, arg2);
}
