// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function CancelAgentExecution(arg1) {
  return window['go']['main']['App']['CancelAgentExecution'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ControlReplay(arg1, arg2, arg3) {
  return window['go']['main']['App']['ControlReplay'](arg1, arg2, arg3);
}

export function CreateHistoryRecord(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateHistoryRecord'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSkill(arg1) {
  return window['go']['main']['App']['CreateSkill'](arg1);
}

export function DeleteHistoryRecord(arg1) {
  return window['go']['main']['App']['DeleteHistoryRecord'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DisableSkill(arg1) {
  return window['go']['main']['App']['DisableSkill'](arg1);
}

export function EnableSkill(arg1) {
  return window['go']['main']['App']['EnableSkill'](arg1);
}

export function ExecuteAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteAgent'](arg1, arg2, arg3);
}

export function ExportSkill(arg1, arg2) {
  return window['go']['main']['App']['ExportSkill'](arg1, arg2);
}

export function GetAgentExecutions() {
  return window['go']['main']['App']['GetAgentExecutions']();
}

export function GetAgentStatus(arg1) {
  return window['go']['main']['App']['GetAgentStatus'](arg1);
}

export function GetAllAgentsStatus() {
  return window['go']['main']['App']['GetAllAgentsStatus']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetEpisodicMemories(arg1, arg2) {
  return window['go']['main']['App']['GetEpisodicMemories'](arg1, arg2);
}

export function GetEvolutionBenefits() {
  return window['go']['main']['App']['GetEvolutionBenefits']();
}

export function GetHistoryRecord(arg1) {
  return window['go']['main']['App']['GetHistoryRecord'](arg1);
}

export function GetHistoryStatistics(arg1, arg2) {
  return window['go']['main']['App']['GetHistoryStatistics'](arg1, arg2);
}

export function GetLogStatistics() {
  return window['go']['main']['App']['GetLogStatistics']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetLogsByAgent(arg1) {
  return window['go']['main']['App']['GetLogsByAgent'](arg1);
}

export function GetLogsByLevel(arg1) {
  return window['go']['main']['App']['GetLogsByLevel'](arg1);
}

export function GetLogsByTimeRange(arg1, arg2) {
  return window['go']['main']['App']['GetLogsByTimeRange'](arg1, arg2);
}

export function GetMCPConfig() {
  return window['go']['main']['App']['GetMCPConfig']();
}

export function GetMCPServerStatus(arg1) {
  return window['go']['main']['App']['GetMCPServerStatus'](arg1);
}

export function GetMCPTools() {
  return window['go']['main']['App']['GetMCPTools']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetRelatedSkills(arg1) {
  return window['go']['main']['App']['GetRelatedSkills'](arg1);
}

export function GetReplayData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReplayData'](arg1, arg2, arg3);
}

export function GetReplayState(arg1) {
  return window['go']['main']['App']['GetReplayState'](arg1);
}

export function GetSemanticMemory() {
  return window['go']['main']['App']['GetSemanticMemory']();
}

export function GetSkillDetails(arg1) {
  return window['go']['main']['App']['GetSkillDetails'](arg1);
}

export function GetSkillStats() {
  return window['go']['main']['App']['GetSkillStats']();
}

export function GetSkillVersions(arg1) {
  return window['go']['main']['App']['GetSkillVersions'](arg1);
}

export function GetSkills() {
  return window['go']['main']['App']['GetSkills']();
}

export function GetStartupPhase() {
  return window['go']['main']['App']['GetStartupPhase']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ImportSkill(arg1, arg2) {
  return window['go']['main']['App']['ImportSkill'](arg1, arg2);
}

export function ImportSkillFromOnline(arg1, arg2) {
  return window['go']['main']['App']['ImportSkillFromOnline'](arg1, arg2);
}

export function ImportSkillFromURL(arg1) {
  return window['go']['main']['App']['ImportSkillFromURL'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListOnlineSources() {
  return window['go']['main']['App']['ListOnlineSources']();
}

export function LogMessage(arg1, arg2) {
  return window['go']['main']['App']['LogMessage'](arg1, arg2);
}

export function LogMessageWithDetails(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['LogMessageWithDetails'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function QueryHistoryRecords(arg1) {
  return window['go']['main']['App']['QueryHistoryRecords'](arg1);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RollbackSkill(arg1, arg2) {
  return window['go']['main']['App']['RollbackSkill'](arg1, arg2);
}

export function SearchOnlineSkills(arg1, arg2) {
  return window['go']['main']['App']['SearchOnlineSkills'](arg1, arg2);
}

export function SearchSkills(arg1, arg2) {
  return window['go']['main']['App']['SearchSkills'](arg1, arg2);
}

export function StartReplay(arg1, arg2) {
  return window['go']['main']['App']['StartReplay'](arg1, arg2);
}

export function SubscribeToReplayEvents(arg1) {
  return window['go']['main']['App']['SubscribeToReplayEvents'](arg1);
}

export function TestMCPServerConnection(arg1) {
  return window['go']['main']['App']['TestMCPServerConnection'](arg1);
}

export function UpdateHistoryRecord(arg1, arg2) {
  return window['go']['main']['App']['UpdateHistoryRecord'](arg1, arg2);
}

export function UpdateMCPConfig(arg1) {
  return window['go']['main']['App']['UpdateMCPConfig'](arg1);
}

export function UpdateMCPServer(arg1, arg2) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1, arg2);
}

export function UpdateSkill(arg1, arg2) {
  return window['go']['main']['App']['UpdateSkill'](arg1, arg2);
}

export function ValidateSkill(arg1) {
  return window['go']['main']['App']['ValidateSkill'](arg1);
}
