// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAgentExecution(arg1:string):Promise<void>;

export function ExecuteAgent(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function GetAgentExecutions():Promise<Array<Record<string, any>>>;

export function GetAgentStatus(arg1:string):Promise<Record<string, any>>;

export function GetAllAgentsStatus():Promise<Record<string, any>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetLogs():Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function HealthCheck():Promise<Record<string, any>>;

export function ListAgents():Promise<Array<Record<string, any>>>;

export function LogMessage(arg1:string,arg2:string):Promise<void>;
